### ISSUE TITLE
[ERR_REQUIRE_ESM] [ERR_REQUIRE_ESM]: Must use import to load ES Module: /project/node_modules/crypto-random-string/index.js

### ISSUE THREAD

**Issue by whileoneloop** [sindresorhus/crypto-random-string#38] opened 2021-04-13 05:47 UTC
Error using version `4.0.0`, using node `v12.16.2`, rolling back to `3.2.0` works.  The error output is:

```sh
W20210413-13:42:32.053(8)? (STDERR) Error [ERR_REQUIRE_ESM] [ERR_REQUIRE_ESM]: Must use import to load ES Module: /project/node_modules/crypto-random-string/index.js
W20210413-13:42:32.053(8)? (STDERR) require() of ES modules is not supported.
W20210413-13:42:32.053(8)? (STDERR) require() of /project/node_modules/crypto-random-string/index.js from /project/profit-app-both-shared/generateRowId.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
W20210413-13:42:32.054(8)? (STDERR) Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /project/node_modules/crypto-random-string/package.json.
W20210413-13:42:32.054(8)? (STDERR) 
```

**Comment by sindresorhus** [comment] 2021-04-13 06:32
Duplicate of #36

**Closed** 2021-04-13 06:32 UTC

**Comment by brianbancroft** [comment] 2021-04-15 03:35
Hey there, just wanted to flag that this also takes place if you're using NextJS with the default Webpack 4 and no custom transpilation of the API functions. I'm not asking that anything be done, and I'm hoping this will prevent another duplicate issue from being carved.

- If you're running into this error with Next JS, sticking with the latest version 3 of this package will work, and it'll likely work well for your ends.

**Comment by whileoneloop** [comment] 2021-04-15 03:48
I saw the issue with 4.x on a meteorjs project, downgrading back to 3.x solved the problem.
