### ISSUE TITLE
Unable to use the library in NodeJS with Typescript

### ISSUE THREAD

**Issue by NoSoup4you2** [sindresorhus/crypto-random-string#39] opened 2021-04-20 02:05 UTC
I used the Library before in version 2.X and it worked fine. After upgrading I get a typescript compile error which reads..

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\WebstormProjects\crm-api-type\node_modules\crypto-random-string\index.js
require() of ES modules is not supported.
require() of C:\Users\WebstormProjects\crm-api-type\node_modules\crypto-random-string\index.js from C:\Users\WebstormProjects\crm-api-type\src\helper\user-security.ts is an ES module file as it
 is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\WebstormProjects\crm-api-type\node_modules\crypto-random-string\package.json.

This is how i declared the library in my module
`import cryptoRandomString from 'crypto-random-string';`

So not sure what i am missing here, i dont require but import your library but still get this error

**Comment by sindresorhus** [comment] 2021-04-20 06:15
Duplicate of #36

**Closed by sindresorhus** 2021-04-20 06:15 UTC
